# Sample MCP Configuration File
# Copy this file to mcp_config.yaml and update with your values

version: "1.0"

# Example Claude MCP Server Configuration
claude:
  enabled: true
  endpoint: "https://api.anthropic.com/v1/mcp"
  authentication:
    type: bearer
    token: "your-claude-api-key-here"
  configuration:
    api_version: "2024-01-01"
    model: "claude-3-opus-20240229"
    max_tokens: 4096
    temperature: 0.7
    system_prompt: |
      You are an AI assistant helping with document processing.

# Example File System MCP Server
filesystem:
  enabled: false
  endpoint: "http://mcp-filesystem:3000"
  authentication:
    type: none
  configuration:
    allowed_paths:
      - "/app/data"
    max_file_size: 10485760

# Example GitHub MCP Server
github:
  enabled: false
  endpoint: "https://api.github.com"
  authentication:
    type: bearer
    token: "your-github-token-here"
  configuration:
    api_version: "2022-11-28"
    organization: "your-org"

# Hook Configuration
hooks:
  pre_connect:
    enabled: true
    timeout: 5
    
  pre_request:
    enabled: true
    timeout: 2
    rate_limit:
      requests_per_minute: 60

# Rule Configuration
rules:
  request_limits:
    max_request_size: 10485760  # 10MB
    
  timeouts:
    default_timeout: 30
    
  rate_limiting:
    enabled: true
    global_limit: 1000