blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Cyarun/Legal-AI-Agents-IND/wiki
    about: Check our documentation for answers
  - name: Community Discussions
    url: https://github.com/Cyarun/Legal-AI-Agents-IND/discussions
    about: Ask questions and discuss with the community
  - name: Security Issues
    url: https://github.com/Cyarun/Legal-AI-Agents-IND/security/policy
    about: Please report security vulnerabilities here