version: '3.8'

services:
  neo4j:
    image: neo4j:5.26-community
    container_name: legal-graphiti-neo4j
    environment:
      - NEO4J_AUTH=neo4j/legalpassword
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2g
      - NEO4J_server_memory_pagecache_size=512m
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    networks:
      - legal-graphiti-network
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  legal-graphiti-mcp:
    build:
      context: .
      dockerfile: Dockerfile.legal
    container_name: legal-graphiti-mcp-server
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=legalpassword
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=gpt-4o-mini
      - SMALL_MODEL_NAME=gpt-4o-mini
      - LLM_TEMPERATURE=0.1
      - SEMAPHORE_LIMIT=10
      - TRANSPORT=sse
    ports:
      - "8000:8000"  # SSE endpoint
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - legal-graphiti-network
    volumes:
      - ./legal_data:/app/legal_data
      - ./logs:/app/logs

  # Optional: Neo4j Browser for visualization
  neo4j-browser:
    image: neo4j:5.26-community
    container_name: legal-graphiti-browser
    command: neo4j-admin server console
    environment:
      - NEO4J_browser_remote__content__hostname__whitelist=*
      - NEO4J_browser_post__connect__cmd=play https://guides.neo4j.com/intro-neo4j-exercises/
    ports:
      - "7475:7474"  # Alternative browser port
    depends_on:
      - neo4j
    networks:
      - legal-graphiti-network

networks:
  legal-graphiti-network:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins: